project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  author: "John Doe"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - basic_data_types.qmd
    - factors.qmd
    - joins.qmd
    - shape_files.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    execute:
      echo: true

editor: visual

